### ISSUE TITLE
Intermittent test failures

### ISSUE THREAD

**Issue by hansenc** [jhalterman/expiringmap#19]
As I was working on #17, I noticed that some tests were failing intermittently. To see if it was caused by the code I added, I checked out the current HEAD on master (78d8f8d1807d7690cdd7cd478de15a750c852064) and ran `for i in {1..100}; do mvn test; done` . Out of 100 executions, I got 9 failures as follows.

7 of these:
```
testExpectedExpiration(net.jodah.expiringmap.ExpiringMapTest)  Time elapsed: 0.059 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at net.jodah.expiringmap.ExpiringMapTest.testExpectedExpiration(ExpiringMapTest.java:589)
```

2 of these:
```
shouldNotReschedulePutsWithSameValue(net.jodah.expiringmap.ExpiringMapTest)  Time elapsed: 0.11 sec  <<< FAILURE!
java.lang.AssertionError: expected [null] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotSame(Assert.java:490)
	at org.testng.Assert.assertNull(Assert.java:426)
	at org.testng.Assert.assertNull(Assert.java:415)
	at net.jodah.expiringmap.ExpiringMapTest.shouldNotReschedulePutsWithSameValue(ExpiringMapTest.java:96)
```

I'm using Java 1.8.0_25 (Oracle) and Maven 3.2.5 on Mac OS X 10.10.4. I don't have time to look into this further at the moment, but I suspect the issue may be the tests themselves rather than the code under test.

**Comment by jhalterman** [comment]
The test suite could probably use some attention overall, but some of the tests, these included, make assumptions about the timing of things happening in other threads - assumptions that aren't always correct. Just pushed a commit that I hope will address this for these two tests. Thanks!
