### ISSUE TITLE
Google App Engine support

### ISSUE THREAD

**Issue by apkelly** [jhalterman/expiringmap#26]
Hi, 

I get the following error when trying to use ExpiringMap on Google App Engine.

`java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThreadGroup")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:382)
	at java.security.AccessController.checkPermission(AccessController.java:572)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.ThreadGroup.checkAccess(ThreadGroup.java:315)
	at java.lang.Thread.init(Thread.java:391)
	at java.lang.Thread.init(Thread.java:349)
	at java.lang.Thread.<init>(Thread.java:548)
	at net.jodah.expiringmap.internal.NamedThreadFactory.newThread(NamedThreadFactory.java:23)
	at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:600)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:943)
	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1635)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:526)
	at java.util.concurrent.Executors$DelegatedScheduledExecutorService.schedule(Executors.java:689)
	at net.jodah.expiringmap.ExpiringMap.scheduleEntry(ExpiringMap.java:1190)`

**Comment by apkelly** [comment]
https://cloud.google.com/appengine/docs/java/runtime#threads

**Comment by jhalterman** [comment]
From a quick search, it looks like app engine does not allow you to create threads using the standard JDK APIs. Instead you have to use special app engine APIs, so... not much we can do about that I'm afraid. I'd be interested to know how other libraries may have worked around this, but I don't have any good ideas off the top of my head.

**Comment by apkelly** [comment]
I think you can create Threads, see link I included. Is there a way to replace the implementation of the Executor that times out the cache entries?

> An application can

Implement java.lang.Runnable; and
Create a thread factory by calling com.google.appengine.api.ThreadManager.currentRequestThreadFactory()
call the factory's newRequestThread method, passing in the Runnable, newRequestThread(runnable)
or use the factory object returned by com.google.appengine.api.ThreadManager.currentRequestThreadFactory() with an ExecutorService (e.g., call Executors.newCachedThreadPool(factory)).

**Comment by jhalterman** [comment]
@apkelly I just submitted a commit that adds `ExpiringMap.setThreadFactory(ThreadFactory)` support. See #27, try the code, and tell me what you think. I'll have to rely on you since I'm not an app engine user...

**Comment by jhalterman** [comment]
Will assume this is good. Closing for now. Re-open if this doesn't work out.

**Comment by apkelly** [comment]
Did you see my comment on your commit? There is a small bug, but other than that it all works perfectly. If you fix the bug can you merge and release?

Thanks,

Andy.

**Comment by jhalterman** [comment]
@apkelly Yep, I fixed the commit based on your comment. The code is merged and has been released as - 0.5.3 (could take an hour or two to sync with maven central).
