### ISSUE TITLE
Illegal access issue

### ISSUE THREAD

**Issue by a9289010767** [jhalterman/expiringmap#35]
java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [net.jodah.expiringmap.ExpiringMap$EntryTreeHashMap$ExpiringEntryIterator]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1325)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1313)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1178)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1139)
	at net.jodah.expiringmap.ExpiringMap$EntryTreeHashMap.valuesIterator(ExpiringMap.java:440)
	at net.jodah.expiringmap.ExpiringMap$5.run(ExpiringMap.java:1292)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jhalterman** [comment]
It looks like Catalina is throwing this exception, not ExpiringMap:

https://tomcat.apache.org/tomcat-8.0-doc/api/org/apache/catalina/loader/WebappClassLoaderBase.html#checkStateForResourceLoading(java.lang.String)

**Comment by a9289010767** [comment]
Hi jhalterman, I have updated to your new version of expiringMap and it seems like issue has been resolved. Thanks for your reply by the way. :)

**Comment by jhalterman** [comment]
Good stuff!
